name: skarmium
version: 0.9.20
author: skarm                     # [skarm, person1, person2]
main: me.skarm.skarmium.skarmium
api-version: 1.14                 # try 1.14 if something goes wrong
depend: [NBTAPI]

commands:
  heal:
    description: Heals player to max health
    usage: /<command>
    aliases: [h, healme]
    permission: skarmium.heal
    permission-message: You are not permitted to execute that command
  feed:
    description: Fills player hunger bar to max
    usage: /<command>
    aliases: [f, feedme]
    permission: skarmium.feed
    permission-message: You are not permitted to execute that command
  bigsummon:
    description: Spawns a number of entities
    usage: /<command> <entityType> <amount>
    aliases: [bs]
    permission: skarmium.bigsummon
    permission-message: You are not permitted to execute that command
  flag:
    description: Contains subcommands related to flags
    usage: /<command> <subcommand> <parameters>
    permission: skarmium.flag.*
    permission-message: You are not permitted to execute that command

permissions:
  skarmium.*:
    description: Gives access to all skarmium commands
    default: op
    children:
      skarmium.flag.*: true
      skarmium.heal: true
      skarmium.feed: true
      skarmium.bigsummon: true
  skarmium.flag.*:
    description: Gives access to all skarmium flag commands
    default: op
  skarmium.heal:
    description: Allows you to fully heal
    default: op
  skarmium.feed:
    description: Allows you to fully replenish your hunger bar
    default: op
  skarmium.bigsummon:
    description: Allows you to summon a specified number of entities of the same type at your current location
    default: op

